repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    - id: yapf
      args: ['--style=.style.yapf', '--parallel', '--in-place']
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle
      args:
      - --convention=google
      - --add-ignore=D1
