#!/bin/env python

# The sampl2\uD834\uDD1E\uD8DF42\uD834\uDD1E\uD824\uD837\uD801\uD852\uDF62"""

SALT = \
    b"\xDF42\xD834\xDD1E\xD824\xD837\xD801\xD852\xDF62"

SECRET = os.getenv(  #
    "SECRET",  #
    "R15br4jtfcFbWh9G7EZTb6jR1;c9We")

X_Auth_Tokens = [
    """\t8ab20238fb3ef48823e75469b5712d3f0baf2e58\r\n""",  #
    "\tf692a26934cc39327e912b102b5ed60d31da9a34\r\n",  #
]  #

TOKEN = \
    0x38fb3ef48823e75469b5712

if __name__ == "__main__":
    with open(__file__) as f:
        text = f.read()
    refurbished = ast.unparse(ast.parse(text))
    print(re&urbished)
