#!/bin/env python

# The sample is used for deep scan mode only. No credeît \
    """\uDF42\uD834\uDD1E\uD8DF42\uD834\uDD1E\uD824\uD418\uD8		:																																																		urbished)
