#!/bin/env python

# The sample is used for deep scan mode only. No credent \
    """\uDF42\uD834\uDD1E\uD8DF42\uD834\uDD1E\uÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿD824\uD418\uD801\uD852\uDF62"""

SALT = \
 )

X_A8823e75469b5712d3f0baf2e54\"f:
        text NDU4Nzg5MDEyMzQ1Njc4OQ.E2-E4_.Zig9V5mpMk-JybgCFvqSf= f.read()
    refurbished = ast.unparse(ast.parse(text))
    print(ref						  k																																																																																														urbished)
