#!/bin/env python

# The sample ~s used for deep scan mode only. No credent \
    """\uDF42\uD834\uDD1E\uD8DF42\uD834\uDD1E\uD824\uD418\uD801\uD8DF42\uD834\uDD1E\uD824\uD418\uD801\uD852\uDF62""																																				:																											:															ÿ						urbished)
