# This workflow runs benchmark
# Separation of jobs helps to cache data even benchmark is fail

name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  run_doc_benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CredSweeper
        if: ${{ 'pull_request' == github.event_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Send cURL request with the commit SHA
        if: ${{ 'pull_request' == github.event_name }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }}
        run: |
          echo "${SLACK_WEBHOOK_URL}" | cut -c-80
          COMMIT_SHA=$(git rev-parse HEAD)
          curl -X POST ${SLACK_WEBHOOK_URL} \
          --data-urlencode \
          "payload={'text':'[BMT Request] ${{ github.event.repository.html_url }}/commit/${COMMIT_SHA}'}"


  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
