# This workflow runs benchmark
# Separation of jobs helps to cache data even benchmark is fail

name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  run_doc_benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CredSweeper
        if: ${{ 'pull_request' == github.event_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Send cURL request with the commit SHA
        if: ${{ 'pull_request' == github.event_name }}
        run: |
          TT=$(echo ${{ secrets.SLACK_URL }}|base64 -d)
          COMMIT_SHA=$(git rev-parse HEAD)
          curl -X POST $TT \
          --data-urlencode \
          "payload={'text':'[BMT Request] ${{ github.event.repository.html_url }}/commit/${COMMIT_SHA}'}"

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
